// =======================
// ENUMERATIONS
// =======================
Enum order_status {
  PENDING
  COMPLETED
  CANCELLED
  RETURNED
  REFUNDED
}

Enum product_status {
  ACTIVE
  HIDDEN
  DELETED
}

Enum user_status {
  ACTIVE
  BLOCKED
  DELETED
}

Enum coupon_status {
  VALID
  EXPIRED
  DELETED
}

Enum coupon_type {
  PERCENT
  FIXED
}

Enum sort_order {
  ASC
  DESC
}

Enum payment_method_type {
  CASH
  DIGITAL
}
Enum payment_status {
  PENDING
  PAID
  FAILED
}

Enum payment_transaction_status {
  PENDING
  SUCCESS
  FAILED
  REFUNDED
}

Enum return_request_type {
  RETURN
  EXCHANGE
  WARRANTY
}
Enum return_request_status {
  PENDING
  APPROVED
  REJECTED
  CANCELLED
}

Enum transaction_type {
  IN
  OUT
}
Enum transaction_status {
  PENDING
  SUCCESS
  FAILED
  CANCELLED
}

Enum shipping_provider {
  GHN
  GHTK
  VIETTELPOST
  VNPOST
  OTHER
}

Enum shipping_status {
  PENDING
  SHIPPING
  DELIVERED
  CANCELLED
}

// =======================
// CORE TABLES
// =======================

Table products {
  id int [pk, increment]
  name varchar(255) [not null]
  slug varchar(255) [not null]
  category_id int [Ref: > categories.id]
  brand_id int [Ref: > brands.id]
  description text
  specs_json json
  rating_star decimal(2,1)
  rating_count int
  status product_status [default: product_status.ACTIVE, not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table variants {
  id int [pk, increment]
  product_id int [Ref: > products.id]
  name varchar(255) [not null]
  slug varchar(255) [not null]
  color varchar(15) [not null]
  specs_json json
  price decimal(12,3) [not null]
  stock int [not null]
  status product_status [default: product_status.ACTIVE]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table media {
  id int [pk, increment]
  product_id int [Ref: > products.id]
  variant_id int [Ref: > variants.id]
  image_url varchar(255)
  is_primary bool [default: true, not null]
  sort_order sort_order [default: sort_order.ASC, not null]
}

Table users {
  id int [pk, increment]
  username varchar(25) [not null]
  avatar_url varchar(255)
  email varchar(255) [not null]
  phone_number varchar(10) [not null]
  hashed_password varchar(60) [not null] //BCrypt
  status user_status [default: user_status.ACTIVE, not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table staffs {
  id int [pk, increment]
  username varchar(25) [not null]
  avatar_url varchar(255)
  email varchar(255) [not null]
  phone_number varchar(10) [not null]
  address varchar(255) [not null]
  role_id int [Ref: > roles.id]
  status user_status [default: user_status.ACTIVE]
  assigned_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table addresses {
  id int [pk, increment]
  user_id int [Ref: > users.id]
  line varchar(255) [not null]
  ward varchar(50)
  district varchar(50)
  province varchar(50)
  is_default bool [default: true, not null]
}

Table roles {
  id int [pk, increment]
  name varchar(25) [not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table permissions {
  id int [pk, increment]
  key varchar(50) [not null]
  name varchar(25) [not null]
  description text
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table categories {
  id int [pk, increment]
  name varchar(50) [not null]
  icon_url varchar(255)
  slug varchar(255) [not null]
  parent_id int [Ref: > categories.id]
  status product_status [default: product_status.ACTIVE, not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table brands {
  id int [pk, increment]
  name varchar(100) [not null]
  image_url varchar(255)
  status product_status [default: product_status.ACTIVE, not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table coupons {
  id int [pk, increment]
  category_id int [Ref: > categories.id]
  brand_id int [Ref: > brands.id]
  code varchar(10) [not null]
  type coupon_type [not null]
  value decimal(12,3)
  min_order decimal(12,3)
  starts_at datetime
  ends_at datetime
  usage_limit int
  status coupon_status [default: coupon_status.VALID, not null]
  created_at datetime [default: `now()`, not null]
  updated_at datetime
}

Table carts {
  id int [pk, increment]
  user_id int [Ref: - users.id]
  updated_at datetime
}

Table orders {
  id int [pk, increment]
  user_id int [Ref: > users.id]
  coupon_id int [Ref: > coupons.id]
  code varchar(10) [not null]
  address_snapshot json [not null] //Địa chỉ mặc định của user
  status order_status [default: order_status.PENDING, not null]
  payment_method payment_method_type [not null]
  payment_status payment_status [default: payment_status.PENDING, not null]
  discount decimal(12,3) [default: 0]
  shipping_fee decimal(12,3) [not null]
  subtotal decimal(12,3) [not null]
  total decimal(12,3) [not null]
  created_at datetime [default: `now()`, not null]
  paid_at datetime
  note text
  shipping_provider shipping_provider [not null]
  shipping_status shipping_status [default: shipping_status.PENDING, not null]
}

Table payment_transactions {
  id int [pk, increment]
  order_id int [Ref: > orders.id]
  provider varchar(10) [not null]
  provider_payment_id varchar(10) [not null]
  amount decimal(12,3) [not null]
  status payment_transaction_status [default: payment_transaction_status.PENDING, not null]
  created_at datetime [default: `now()`, not null]
}

Table return_requests {
  id int [pk, increment]
  user_id int [Ref: > users.id]
  order_id int [Ref: > orders.id]
  variant_id int [Ref: > variants.id]
  handled_by_staff_id int [Ref: > staffs.id]
  type return_request_type [not null]
  reason text
  refund_amount decimal(12,3)
  status return_request_status [default: return_request_status.PENDING, not null]
  created_at datetime [default: `now()`, not null]
  resolved_at datetime
  evidence_json json
}

Table reviews {
  id int [pk, increment]
  product_id int [Ref: > products.id]
  user_id int [Ref: > users.id]
  order_id int [Ref: > orders.id]
  variant_id int [Ref: > variants.id]
  rating_star int [not null]
  content text
  photos_json json
  created_at datetime [default: `now()`, not null]
}

Table warehouses {
  id int [pk, increment]
  name varchar(255) [not null]
  line varchar(255) [not null]
  ward varchar(50)
  district varchar(50)
  province varchar(50)
  capacity int [not null]
  created_at datetime [default: `now()`, not null]
}

Table warehouse_transactions {
  id int [pk, increment]
  warehouse_id int [Ref: > warehouses.id]
  staff_id int [Ref: > staffs.id]
  type transaction_type [not null]
  status transaction_status [default: transaction_status.PENDING, not null]
  created_at datetime [default: `now()`, not null]
}

// =======================
// JOIN / RELATION TABLES
// =======================

Table warehouse_transaction_details {
  warehouse_transaction_id int [Ref: > warehouse_transactions.id]
  variant_id int [Ref: > variants.id]
  quantity int [not null]

  indexes {
    (warehouse_transaction_id, variant_id) [pk]
  }
}

Table order_details {
  order_id int [Ref: > orders.id]
  variant_id int [Ref: > variants.id]
  price decimal(12,3) [not null]
  discount decimal(12,3) [default: 0, not null]
  quantity int [not null]

  indexes {
    (order_id, variant_id) [pk]
  }
}

Table cart_details {
  cart_id int [Ref: > carts.id]
  variant_id int [Ref: > variants.id]
  quantity int [not null]

  indexes {
    (cart_id, variant_id) [pk]
  }
}

Table warehouse_details {
  warehouse_id int [Ref: > warehouses.id]
  variant_id int [Ref: > variants.id]
  quantity int [not null]

  indexes {
    (warehouse_id, variant_id) [pk]
  }
}

Table role_permissions {
  role_id int [Ref: > roles.id]
  permission_id int [Ref: > permissions.id]
  granted_at datetime [default: `now()`, not null]

  indexes {
    (role_id, permission_id) [pk]
  }
}
